Render html from openapi spec generated by typespec
seqeralabs/wave pull request #707
Opened 2024-10-21 08:50 UTC by munishchouhan

This PR will do the followings:
1. Move typespec to resources
2. create gradle task to install and compile typespec to generate openapi.yaml
3. create html to render openapi using rapiddoc

2024-10-21 09:00 UTC, munishchouhan commented
> Not sure we should include this stuff within wave backend

so we want to host them separately?

2024-10-21 09:07 UTC, pditommaso commented
Think would make more sense, either in the main docs or a mini dedicated app. Tagging @ewels

2024-10-21 09:26 UTC, ewels commented
Yup, I'd expect to keep just the typespec in the repo and have everything else compiled and hosted separately. Where that happens I don't have a strong opinion on - either the Wave service itself? Or the docs website? (NB: Not the docs _repo_).

Tagging @llewellyn-sl @andrew-dawson-seqera

2024-10-21 09:28 UTC, ewels commented
Looks like the Platform API docs are hosted at https://cloud.seqera.io/openapi/index.html

So Wave docs could live at https://wave.seqera.io/openapi/index.html for example?

2024-10-21 09:34 UTC, pditommaso commented
That's fine. Then we need to create a mini nginx service to render the docs.

2024-10-23 11:07 UTC, munishchouhan commented
<img width="752" alt="Screenshot 2024-10-23 at 13 07 15" src="https://github.com/user-attachments/assets/c25874f8-8371-453b-ab9c-71d01b8bc50c">

2024-10-24 07:51 UTC, pditommaso requested changes
Nice, then we need to including this container build in the same process  for the wave app container.

2024-10-25 08:53 UTC, munishchouhan commented
> Nice, then we need to including this container build in the same process for the wave app container.

ok sure

2024-11-18 15:54 UTC, ewels commented
Not sure what the web UI is there - any chance that we can use Swagger so that it has the same look + feel as https://cloud.seqera.io/openapi/index.html please?

2024-11-20 14:05 UTC, munishchouhan commented
> Not sure what the web UI is there - any chance that we can use Swagger so that it has the same look + feel as https://cloud.seqera.io/openapi/index.html please?

ok I will look into it

2025-01-15 14:18 UTC, munishchouhan commented
now using swagger ui
<img width="1487" alt="Screenshot 2025-01-15 at 15 17 33" src="https://github.com/user-attachments/assets/ac4405c8-7ef6-4635-8f98-76f9132f1745" />

2025-01-15 14:20 UTC, pditommaso commented
Nice

2025-01-15 14:21 UTC, pditommaso commented
What's missing to make the live?

2025-01-15 14:22 UTC, munishchouhan commented
> What's missing to make the live?

I will do a test  release, once it's successful, then I will work on infra part

2025-01-16 13:57 UTC, gavinelder commented on typespec/index.html
> +            url: "tsp-output/@typespec/openapi3/openapi.yaml",
Can we change this URL so it is looking for resources under a single path of `/openapi`

```suggestion
            url: "openapi/openapi.yaml",
```

2025-01-16 13:57 UTC, gavinelder commented on typespec/Dockerfile
> +COPY tsp-output/@typespec/openapi3/openapi.yaml /usr/share/nginx/html/tsp-output/@typespec/openapi3/
```suggestion
COPY tsp-output/@typespec/openapi3/openapi.yaml /usr/share/nginx/html/openapi/openapi.yaml
```

2025-01-16 14:09 UTC, munishchouhan commented on typespec/index.html
> +            url: "tsp-output/@typespec/openapi3/openapi.yaml",
changing it to a custom path, makes it harder to test locally the API changes, so keeping it same as typespec output path servers in every env

2025-01-16 17:56 UTC, gavinelder commented on typespec/index.html
> +            url: "tsp-output/@typespec/openapi3/openapi.yaml",
This would require an additional ingress path to be created for the route `tsp-output` on the kubernetes deployment.

2025-01-16 18:02 UTC, gavinelder commented on typespec/index.html
> +            url: "tsp-output/@typespec/openapi3/openapi.yaml",
Looking at Platform API Spec.

The UI is at 
https://cloud.seqera.io/openapi

With the schema being hosted at 
https://cloud.seqera.io/openapi/seqera-api-latest.yml

I still feel like we should align to 

https://wave.seqera.io/openapi/

And 

https://cloud.seqera.io/openapi/somefile.yaml

instead of hosting it on `tsp-output` especially since this change only impacts the docker container and not local dev flows.

2025-01-17 09:06 UTC, munishchouhan commented on typespec/index.html
> +            url: "tsp-output/@typespec/openapi3/openapi.yaml",
in the case of the platform, it's different because Openapi resides inside the platform, and in the case of Wave, it's a different app. I tried these changes but still facing the routing issue

2025-01-20 13:02 UTC, munishchouhan commented
tested with new port and wave dev:
<img width="1713" alt="Screenshot 2025-01-20 at 14 01 47" src="https://github.com/user-attachments/assets/90ea717e-8a97-4bb6-8bbe-2117c7e01f08" />

2025-01-20 15:37 UTC, gavinelder commented on typespec/routes.tsp
> +@server("https://wave.stage-seqera.io", "wave stage endpoint")
I wonder if this could be the base URL

2025-01-20 15:44 UTC, munishchouhan commented on typespec/routes.tsp
> +@server("https://wave.stage-seqera.io", "wave stage endpoint")
its selected by default
<img width="556" alt="Screenshot 2025-01-20 at 16 43 44" src="https://github.com/user-attachments/assets/47a9ef49-acd9-4621-838a-3c5ea7c4731c" />

2025-01-20 18:02 UTC, munishchouhan commented on typespec/routes.tsp
> +@server("https://wave.stage-seqera.io", "wave stage endpoint")
please let me know, if you meant something else

2025-01-20 18:02 UTC, munishchouhan commented
@pditommaso it is ready for review
tested:
<img width="1472" alt="Screenshot 2025-01-20 at 19 01 13" src="https://github.com/user-attachments/assets/45685e76-c07e-4b62-b388-f19ab9d77108" />

2025-01-21 09:37 UTC, pditommaso requested changes

2025-01-21 09:37 UTC, pditommaso commented on .github/workflows/typespec.yml
> +        if: "contains(github.event.head_commit.message, '[release docs]')"
```suggestion
      - name: Release OpenAPI docs
        if: "contains(github.event.head_commit.message, '[release]')"
```

2025-01-21 09:37 UTC, pditommaso commented on .github/workflows/typespec.yml
> +        if: "contains(github.event.head_commit.message, '[release docs]')"
better to keep this aligned with the release

2025-01-21 09:45 UTC, munishchouhan commented on .github/workflows/typespec.yml
> +        if: "contains(github.event.head_commit.message, '[release docs]')"
we need to make sure, change the version in route.tsp also at the time of release

2025-01-21 20:43 UTC, munishchouhan commented on typespec/routes.tsp
> +@server("https://wave.stage-seqera.io", "wave stage endpoint")
I think you meant if we can use the URL that we used to access the swagger UI
but typespec currently does not support it
https://typespec.io/docs/libraries/http/reference/decorators/#@TypeSpec.Http.server

2025-01-24 13:59 UTC, munishchouhan commented
tested in dev

https://github.com/user-attachments/assets/96b27999-346b-4772-9711-5e36142015a5

2025-01-24 14:27 UTC, pditommaso commented on src/main/groovy/io/seqera/wave/controller/OpenAPIController.groovy
> +    }
Let's move this here, that's done mostly for it 

https://github.com/seqeralabs/wave/blob/5d5fd91352744febfc010708e326467d24bef798/src/main/groovy/io/seqera/wave/controller/ServiceInfoController.groovy#L45-L60

2025-01-24 14:28 UTC, pditommaso commented on typespec/tag-and-push-docs.sh
`typespec/tag-and-push-openapi.sh`

2025-01-24 14:28 UTC, pditommaso commented on typespec/routes.tsp
> +      v1: "1.16.8",
should this be updated manually?

2025-01-24 14:35 UTC, munishchouhan commented on typespec/routes.tsp
> +      v1: "1.16.8",
yes for now, typespec.yml only runs when there is a change in typespec folder and to make a doc release, we need a change there in the commit

2025-01-24 15:18 UTC, munishchouhan commented on typespec/routes.tsp
> +      v1: "1.16.8",
yes, that can be an option, i will move doc release to build.yml too
to not rely on typespec chnages

2025-01-24 15:19 UTC, munishchouhan commented on typespec/routes.tsp
> +      v1: "1.16.8",
ok better addin  VERSION path in typespec.yml, so that it runs when we change VERSION

2025-01-26 20:46 UTC, munishchouhan commented
Tested successfully in dev
<img width="631" alt="Screenshot 2025-01-26 at 21 45 45" src="https://github.com/user-attachments/assets/c4f43a62-1f59-4d37-801e-e6a42cd45e78" />
<img width="912" alt="Screenshot 2025-01-26 at 21 45 21" src="https://github.com/user-attachments/assets/3b8910f4-a272-4607-8d9d-9d8773cf2da5" />

2025-01-28 09:20 UTC, pditommaso commented on typespec/tag-and-push-docs.sh
`tag-and-push-openapi.sh`

2025-01-28 09:32 UTC, munishchouhan commented on typespec/tag-and-push-docs.sh
done

2025-01-28 09:40 UTC, pditommaso commented on typespec/Dockerfile
> +RUN sed -i 's/listen       80;/listen       9080;/' /etc/nginx/conf.d/default.conf
They provide an un unprivileged image that does not require this https://hub.docker.com/r/nginxinc/nginx-unprivileged

2025-01-28 10:47 UTC, munishchouhan commented on typespec/Dockerfile
> +RUN sed -i 's/listen       80;/listen       9080;/' /etc/nginx/conf.d/default.conf
done

2025-01-29 11:02 UTC, pditommaso approved these changes

2025-01-29 11:34 UTC, merged